#! /bin/bash
YELLOWORANGE="\e[38;5;221m"
GREEN="\e[38;5;76m"
PURPLE="\e[38;5;5m"
BLUE="\e[38;5;4m"
RED="\e[38;5;9m"
TEAL="\e[38;5;14m"
GREENISH="\e[38;5;151m"
STOP="\e[38;5;15m"
printf "${GREEN}"
printf "===============================================================================\n \n"
printf "${STOP}"
printf "${YELLOWORANGE}"
figlet  -f doom "CAR PARKING X"
printf "${STOP}"
printf "${GREEN}"
printf "=================================================================================\n"
printf "${STOP}"
printf "\n"
printf "${PURPLE}"
printf "[1] See every city added     \n"
printf "[2] See every car in a city  \n"
printf "${STOP}"
printf "${GREEN}"
printf "[3] add a new city           \n"
printf "[4] add a new car to a city     \n"
printf "${STOP}"
printf "${RED}"
printf "[5] remove a car from a city    \n"
printf "[6] remove a city from the list    \n"
printf "${STOP}"
printf "${TEAL}"
printf "[7] plan a trip with us    \n"
printf "[8] read option from file    \n"
printf "${STOP}"
printf "${YELLOWORANGE}"
printf "[9] exit\n"
printf "${STOP}"
printf "\n"
printf "${YELLOWORANGE}"
printf "What do you wanna do? \n"
printf "\n"
printf "${STOP}"
